### ISSUE TITLE
Energy Predictors Review

### ISSUE THREAD

**Issue by educanovas93** [fluidos-project/general-activities#13]
Review the installation information and report any problems you had when deploying the component, also report if there are unit or integration tests, if they are well formed, add screenshots of the deployments and comments about what may be missing.

https://github.com/fluidos-project/fluidos-energy-predictor

**Comment by tok43** [comment]
Following things have been fixed:
- CI/CD pipeline
- Purged temporary files from the training sample archive

Following issue have been raised:
- https://github.com/risingfbk/fluidos-energy-predictor/issues/2
- https://github.com/risingfbk/fluidos-energy-predictor/issues/1

Following PR have been submitted:
- https://github.com/fluidos-project/fluidos-energy-predictor/pull/1

**Comment by tok43** [comment]
Issues have been fixed and PR merged. The review is completed successfully.
