### ISSUE TITLE
KubeCtl Plugin Review

### ISSUE THREAD

**Issue by educanovas93** [fluidos-project/general-activities#16]
Review the installation information and report any problems you had when deploying the component, also report if there are unit or integration tests, if they are well formed, add screenshots of the deployments and comments about what may be missing.

https://github.com/fluidos-project/kubectl-fluidos-plugin

**Comment by ggari-robotnik** [comment]
The plugin install correctlly using the tag command in ubuntu 22.04:
```bash
pip install git+https://github.com/fluidos-project/kubectl-fluidos-plugin@0.0.1
```

![Image](https://github.com/fluidos-project/general-activities/assets/61705660/381f48c0-097d-4ee5-acd6-810971bc769f)

**Comment by ggari-robotnik** [comment]
failed test on readme:

openned issue [Quick Start guide MSPL test fails](https://github.com/fluidos-project/kubectl-fluidos-plugin/issues/18)

**Comment by ggari-robotnik** [comment]
Pull request opened to solve this issue:
[Fix failure missing MSPL api](https://github.com/fluidos-project/kubectl-fluidos-plugin/pull/19)

**Comment by ggari-robotnik** [comment]
New release with everything fixed:
[v0.0.2](https://github.com/fluidos-project/kubectl-fluidos-plugin/tree/v0.0.2)
