### ISSUE TITLE
Write the Quick Start guide

### ISSUE THREAD

**Issue by ggari-robotnik** [fluidos-project/general-activities#3]

**Comment by educanovas93** [comment]
Awesome Readme repository
https://github.com/matiassingers/awesome-readme?tab=readme-ov-file

Good looking Readme Example
https://github.com/AntonioFalcaoJr/EventualShop?tab=readme-ov-file#toolbox-tech-stack

**Comment by educanovas93** [comment]
i made some changes in to have a goodlook readme as @frisso requested, the changes are here : 
https://github.com/fluidos-project/quick-start-guide/tree/goodlook-readme

I did a pull request here: 

https://github.com/fluidos-project/quick-start-guide/pull/5

**Comment by educanovas93** [comment]
First version of quickstart guide finished with WP Contributions for D9.2 First release of the integrated meta-OS

 https://github.com/fluidos-project/quick-start-guide/
