### ISSUE TITLE
Finish structure of D9.2

### ISSUE THREAD

**Issue by ggari-robotnik** [fluidos-project/general-activities#4]

**Comment by educanovas93** [comment]
Document URL
https://docs.google.com/document/d/1LZDjIwL61G7zubRJ3xJ1lrqPYGKVb7hA/edit?usp=sharing&ouid=117836554085026481320&rtpof=true&sd=true

**Comment by educanovas93** [comment]
Deliverable 9.2

——Scrum T9.1

-How is scrum being done
-What resources are we providing for scrum to be done
-How minutes are transformed into kanban boards
-How sprints are managed
-Guidelines that have been created to work with sprint boards, sprint management and thus be able to do better scrums
-Creation of sprint boards in github everything organized, with issues, corresponding to code projects or general activities

——CI/CD T9.2

-What has been carried out in CI/CD terms
-Defined Continuous integration plan
-Instructions and guidelines for github repositories
-Creation of repositories and management through projects on github user hierarchies and contributions with pull requests
-Guides that have been created to help partners
-Pipelines that have been created
-How the runners have been created for the entire fluids project (POLITO)
-How github actions and github are being used in all this


——Performance T9.3
-What KPIs have been obtained?
-How KPI'S are evaluated
-Who evaluates those KPIs?
-Ways to evaluate KPIs automatically with actions in continuous integration pipelines,  (tests, Software.com action, sonarqube...)

**Comment by educanovas93** [comment]
Structure finalished
