### ISSUE TITLE
Provide Scrum management documentation

### ISSUE THREAD

**Issue by ggari-robotnik** [fluidos-project/general-activities#6]
Provide an example and documentation of scrum management to other work package

**Comment by educanovas93** [comment]
Sprint management Document URL :
https://docs.google.com/document/d/170w19guOOYhfDBPmVpwbsCHnRdy7KzpSymUZAYxEGeQ/edit?usp=drive_link

**Comment by educanovas93** [comment]
First release of sprint board management: 
https://docs.google.com/document/d/19UXWqq8hj5lIbdpXhqrmlxwwsXHM21Gy/edit?usp=drive_link&ouid=117836554085026481320&rtpof=true&sd=true

next steps:
-add changes
-adjust to Fluidos doc format
-add sprint boards guide to scrum guide

**Comment by educanovas93** [comment]
I think that We can close this with the current documentation is ok.

Thank you guys!
